export const initialItems = [
  {
    text: "Доллар США",
    symbol: "$",
    code: "USD",
    currencyCode: "US",
  },
  {
    text: "Евро",
    symbol: "€",
    code: "EUR",
    currencyCode: "EU",
  },
  {
    text: "Фунт стерлингов",
    symbol: "£",
    code: "GBP",
    currencyCode: "GB",
  },
  {
    text: "Японская иена",
    symbol: "¥",
    code: "JPY",
    currencyCode: "JP",
  },
  {
    text: "Индийская рупия",
    symbol: "₹",
    code: "INR",
    currencyCode: "IN",
  },
  {
    text: "Австрал. доллар",
    symbol: "A$",
    code: "AUD",
    currencyCode: "AU",
  },
  {
    text: "Канадский доллар",
    symbol: "C$",
    code: "CAD",
    currencyCode: "CA",
  },
  {
    text: "Швейцарский франк",
    symbol: "CHF",
    code: "CHF",
    currencyCode: "CH",
  },
  {
    text: "Китайский юань",
    symbol: "¥",
    code: "CNY",
    currencyCode: "CN",
  },
  {
    text: "Шведская крона",
    symbol: "kr",
    code: "SEK",
    currencyCode: "SE",
  },
  {
    text: "Новозеланд. доллар",
    symbol: "NZ$",
    code: "NZD",
    currencyCode: "NZ",
  },
  {
    text: "Мексиканское песо",
    symbol: "$",
    code: "MXN",
    currencyCode: "MX",
  },
  {
    text: "Сингапурский доллар",
    symbol: "S$",
    code: "SGD",
    currencyCode: "SG",
  },
  {
    text: "Гонконгский доллар",
    symbol: "HK$",
    code: "HKD",
    currencyCode: "HK",
  },
  {
    text: "Норвежская крона",
    symbol: "kr",
    code: "NOK",
    currencyCode: "NO",
  },
  {
    text: "Южнокорейская вона",
    symbol: "₩",
    code: "KRW",
    currencyCode: "KR",
  },
  {
    text: "Турецкая лира",
    symbol: "₺",
    code: "TRY",
    currencyCode: "TR",
  },
  {
    text: "Российский рубль",
    symbol: "₽",
    code: "RUB",
    currencyCode: "RU",
  },
  {
    text: "Южноафриканский ранд",
    symbol: "R",
    code: "ZAR",
    currencyCode: "ZA",
  },
  {
    text: "Бразильский реал",
    symbol: "R$",
    code: "BRL",
    currencyCode: "BR",
  },
  {
    text: "Малайзийский ринггит",
    symbol: "RM",
    code: "MYR",
    currencyCode: "MY",
  },
  {
    text: "Филиппинское песо",
    symbol: "₱",
    code: "PHP",
    currencyCode: "PH",
  },
  {
    text: "Чешская крона",
    symbol: "Kč",
    code: "CZK",
    currencyCode: "CZ",
  },
  {
    text: "Индонезийская рупия",
    symbol: "Rp",
    code: "IDR",
    currencyCode: "ID",
  },
  {
    text: "Венгерский форинт",
    symbol: "Ft",
    code: "HUF",
    currencyCode: "HU",
  },
  {
    text: "Исландская крона",
    symbol: "kr",
    code: "ISK",
    currencyCode: "IS",
  },
  {
    text: "Израильский шекель",
    symbol: "₪",
    code: "ILS",
    currencyCode: "IL",
  },
  {
    text: "Чилийское песо",
    symbol: "$",
    code: "CLP",
    currencyCode: "CL",
  },
  {
    text: "Пакистанская рупия",
    symbol: "₨",
    code: "PKR",
    currencyCode: "PK",
  },
  {
    text: "Тайский бат",
    symbol: "฿",
    code: "THB",
    currencyCode: "TH",
  },
  {
    text: "Нигерийская найра",
    symbol: "₦",
    code: "NGN",
    currencyCode: "NG",
  },
  {
    text: "Украинская гривна",
    symbol: "₴",
    code: "UAH",
    currencyCode: "UA",
  },
  {
    text: "Колумбийское песо",
    symbol: "$",
    code: "COP",
    currencyCode: "CO",
  },
  {
    text: "Танзанийский шиллинг",
    symbol: "TSh",
    code: "TZS",
    currencyCode: "TZ",
  },
  {
    text: "Аргентинское песо",
    symbol: "$",
    code: "ARS",
    currencyCode: "AR",
  },
  {
    text: "Вьетнамский донг",
    symbol: "₫",
    code: "VND",
    currencyCode: "VN",
  },
  {
    text: "Болгарский лев",
    symbol: "лв",
    code: "BGN",
    currencyCode: "BG",
  },
  {
    text: "Хорватская куна",
    symbol: "kn",
    code: "HRK",
    currencyCode: "HR",
  },
  {
    text: "Румынский лей",
    symbol: "lei",
    code: "RON",
    currencyCode: "RO",
  },
  {
    text: "Белорусский рубль",
    symbol: "Br",
    code: "BYN",
    currencyCode: "BY",
  },
  {
    text: "Албанский лек",
    symbol: "L",
    code: "ALL",
    currencyCode: "AL",
  },
  {
    text: "Армянский драм",
    symbol: "֏",
    code: "AMD",
    currencyCode: "AM",
  },
  {
    text: "Азербайджанский манат",
    symbol: "₼",
    code: "AZN",
    currencyCode: "AZ",
  },
  {
    text: "Боснийская марка",
    symbol: "KM",
    code: "BAM",
    currencyCode: "BA",
  },
  {
    text: "Грузинский лари",
    symbol: "₾",
    code: "GEL",
    currencyCode: "GE",
  },
  {
    text: "Казахстанский тенге",
    symbol: "₸",
    code: "KZT",
    currencyCode: "KZ",
  },
  {
    text: "Киргизский сом",
    symbol: "сом",
    code: "KGS",
    currencyCode: "KG",
  },
  {
    text: "Молдавский лей",
    symbol: "L",
    code: "MDL",
    currencyCode: "MD",
  },
  {
    text: "Македонский денар",
    symbol: "ден",
    code: "MKD",
    currencyCode: "MK",
  },
  {
    text: "Сербский динар",
    symbol: "дин",
    code: "RSD",
    currencyCode: "RS",
  },
  {
    text: "Туркменский манат",
    symbol: "m",
    code: "TMT",
    currencyCode: "TM",
  },
  {
    text: "Узбекский сум",
    symbol: "сўм",
    code: "UZS",
    currencyCode: "UZ",
  },
  {
    text: "Таджикский сомони",
    symbol: "смн",
    code: "TJS",
    currencyCode: "TJ",
  },
];
