export const initialItems = [
  {
    id: 1,
    text: "Доллар США",
    symbol: "$",
    code: "USD",
    countyCode: "US",
  },
  {
    id: 2,
    text: "Евро",
    symbol: "€",
    code: "EUR",
    countyCode: "EU",
  },
  {
    id: 3,
    text: "Фунт стерлингов",
    symbol: "£",
    code: "GBP",
    countyCode: "GB",
  },
  {
    id: 4,
    text: "Японская иена",
    symbol: "¥",
    code: "JPY",
    countyCode: "JP",
  },
  {
    id: 5,
    text: "Индийская рупия",
    symbol: "₹",
    code: "INR",
    countyCode: "IN",
  },
  {
    id: 6,
    text: "Австрал. доллар",
    symbol: "A$",
    code: "AUD",
    countyCode: "AU",
  },
  {
    text: "Канадский доллар",
    symbol: "C$",
    code: "CAD",
    countyCode: "CA",
  },
  {
    text: "Швейцарский франк",
    symbol: "CHF",
    code: "CHF",
    countyCode: "CH",
  },
  {
    text: "Китайский юань",
    symbol: "¥",
    code: "CNY",
    countyCode: "CN",
  },
  {
    text: "Шведская крона",
    symbol: "kr",
    code: "SEK",
    countyCode: "SE",
  },
  {
    text: "Новозеланд. доллар",
    symbol: "NZ$",
    code: "NZD",
    countyCode: "NZ",
  },
  {
    id: 12,
    text: "Мексиканское песо",
    symbol: "$",
    code: "MXN",
    countyCode: "MX",
  },
  {
    id: 13,
    text: "Сингапурский доллар",
    symbol: "S$",
    code: "SGD",
    countyCode: "SG",
  },
  {
    id: 14,
    text: "Гонконгский доллар",
    symbol: "HK$",
    code: "HKD",
    countyCode: "HK",
  },
  {
    id: 15,
    text: "Норвежская крона",
    symbol: "kr",
    code: "NOK",
    countyCode: "NO",
  },
  {
    id: 16,
    text: "Южнокорейская вона",
    symbol: "₩",
    code: "KRW",
    countyCode: "KR",
  },
  {
    id: 17,
    text: "Турецкая лира",
    symbol: "₺",
    code: "TRY",
    countyCode: "TR",
  },
  {
    id: 18,
    text: "Российский рубль",
    symbol: "₽",
    code: "RUB",
    countyCode: "RU",
  },
  {
    id: 19,
    text: "Южноафриканский ранд",
    symbol: "R",
    code: "ZAR",
    countyCode: "ZA",
  },
  {
    id: 20,
    text: "Бразильский реал",
    symbol: "R$",
    code: "BRL",
    countyCode: "BR",
  },
  {
    id: 21,
    text: "Малайзийский ринггит",
    symbol: "RM",
    code: "MYR",
    countyCode: "MY",
  },
  {
    id: 22,
    text: "Филиппинское песо",
    symbol: "₱",
    code: "PHP",
    countyCode: "PH",
  },
  {
    id: 23,
    text: "Чешская крона",
    symbol: "Kč",
    code: "CZK",
    countyCode: "CZ",
  },
  {
    id: 24,
    text: "Индонезийская рупия",
    symbol: "Rp",
    code: "IDR",
    countyCode: "ID",
  },
  {
    id: 25,
    text: "Венгерский форинт",
    symbol: "Ft",
    code: "HUF",
    countyCode: "HU",
  },
  {
    id: 26,
    text: "Исландская крона",
    symbol: "kr",
    code: "ISK",
    countyCode: "IS",
  },
  {
    id: 27,
    text: "Израильский шекель",
    symbol: "₪",
    code: "ILS",
    countyCode: "IL",
  },
  {
    id: 28,
    text: "Чилийское песо",
    symbol: "$",
    code: "CLP",
    countyCode: "CL",
  },
  {
    id: 29,
    text: "Пакистанская рупия",
    symbol: "₨",
    code: "PKR",
    countyCode: "PK",
  },
  {
    id: 30,
    text: "Тайский бат",
    symbol: "฿",
    code: "THB",
    countyCode: "TH",
  },
  {
    id: 31,
    text: "Нигерийская найра",
    symbol: "₦",
    code: "NGN",
    countyCode: "NG",
  },
  {
    id: 32,
    text: "Украинская гривна",
    symbol: "₴",
    code: "UAH",
    countyCode: "UA",
  },
  {
    id: 33,
    text: "Колумбийское песо",
    symbol: "$",
    code: "COP",
    countyCode: "CO",
  },
  {
    id: 34,
    text: "Танзанийский шиллинг",
    symbol: "TSh",
    code: "TZS",
    countyCode: "TZ",
  },
  {
    id: 35,
    text: "Аргентинское песо",
    symbol: "$",
    code: "ARS",
    countyCode: "AR",
  },
  {
    id: 36,
    text: "Вьетнамский донг",
    symbol: "₫",
    code: "VND",
    countyCode: "VN",
  },
  {
    id: 37,
    text: "Болгарский лев",
    symbol: "лв",
    code: "BGN",
    countyCode: "BG",
  },
  {
    id: 38,
    text: "Хорватская куна",
    symbol: "kn",
    code: "HRK",
    countyCode: "HR",
  },
  {
    id: 39,
    text: "Румынский лей",
    symbol: "lei",
    code: "RON",
    countyCode: "RO",
  },
  {
    id: 40,
    text: "Белорусский рубль",
    symbol: "Br",
    code: "BYN",
    countyCode: "BY",
  },
  {
    id: 41,
    text: "Албанский лек",
    symbol: "L",
    code: "ALL",
    countyCode: "AL",
  },
  {
    id: 42,
    text: "Армянский драм",
    symbol: "֏",
    code: "AMD",
    countyCode: "AM",
  },
  {
    id: 43,
    text: "Азербайджанский манат",
    symbol: "₼",
    code: "AZN",
    countyCode: "AZ",
  },
  {
    id: 44,
    text: "Боснийская марка",
    symbol: "KM",
    code: "BAM",
    countyCode: "BA",
  },
  {
    id: 45,
    text: "Грузинский лари",
    symbol: "₾",
    code: "GEL",
    countyCode: "GE",
  },
  {
    id: 46,
    text: "Казахстанский тенге",
    symbol: "₸",
    code: "KZT",
    countyCode: "KZ",
  },
  {
    id: 47,
    text: "Киргизский сом",
    symbol: "сом",
    code: "KGS",
    countyCode: "KG",
  },
  {
    id: 48,
    text: "Молдавский лей",
    symbol: "L",
    code: "MDL",
    countyCode: "MD",
  },
  {
    id: 49,
    text: "Македонский денар",
    symbol: "ден",
    code: "MKD",
    countyCode: "MK",
  },
  {
    id: 50,
    text: "Сербский динар",
    symbol: "дин",
    code: "RSD",
    countyCode: "RS",
  },
  {
    id: 51,
    text: "Туркменский манат",
    symbol: "m",
    code: "TMT",
    countyCode: "TM",
  },
  {
    id: 52,
    text: "Узбекский сум",
    symbol: "сўм",
    code: "UZS",
    countyCode: "UZ",
  },
  {
    id: 53,
    text: "Таджикский сомони",
    symbol: "смн",
    code: "TJS",
    countyCode: "TJ",
  },
];
